services:
  db:
    image: postgres
    restart: always
    environment:
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_SENHA}
      POSTGRES_DB: ${DB_NAME_LABOR}
      PGDATA: /var/lib/postgresql/data
    ports:
      - "5432:5432"
    volumes:
      - ./data:/var/lib/postgresql/data

