CREATE TABLE empresas
(
    id               BIGINT GENERATED BY DEFAULT AS IDENTITY   NOT NULL,
    razao_social     VARCHAR(100)                              NOT NULL,
    nome_fantasia    VARCHAR(100),
    cnpj             VARCHAR(14)                               NOT NULL,
    ativo            BOOLEAN DEFAULT TRUE                      NOT NULL ,
    data_criacao     TIMESTAMP WITHOUT TIME ZONE DEFAULT now() NOT NULL,
    data_atualizacao TIMESTAMP WITHOUT TIME ZONE               NOT NULL,
    CONSTRAINT pk_empresas PRIMARY KEY (id)
);