CREATE TABLE turmas
(
    id               BIGINT GENERATED BY DEFAULT AS IDENTITY   NOT NULL,
    descricao        VARCHAR(80)                               NOT NULL,
    controle         VARCHAR(10)                               NOT NULL,
    ativo            BOOLEAN                                   NOT NULL,
    data_criacao     TIMESTAMP WITHOUT TIME ZONE DEFAULT now() NOT NULL,
    data_atualizacao TIMESTAMP WITHOUT TIME ZONE               NOT NULL,
    empresa_id       BIGINT                                    NOT NULL,
    CONSTRAINT pk_turma PRIMARY KEY (id)
);

ALTER TABLE turmas ADD CONSTRAINT fk_turemp_empresa FOREIGN KEY (empresa_id) REFERENCES empresas (id);
