CREATE TABLE tarefas
(
    id                BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    descricao         VARCHAR(80)                             NOT NULL,
    valor_minimo      DECIMAL(19, 4)                          NOT NULL,
    valor_maximo      DECIMAL(19, 4)                          NOT NULL,
    quantidade_minima DECIMAL(19, 4)                          NOT NULL,
    quantidade_maxima DECIMAL(19, 4)                          NOT NULL,
    controle          VARCHAR(10)                             NOT NULL,
    empresa_id        BIGINT                                  NOT NULL,
    ativo             BOOLEAN default true                    NOT NULL,
    data_criacao      timestamp default now() not null,
    data_atualizacao  timestamp default now() not null,
    CONSTRAINT pk_tarefas PRIMARY KEY (id)
);

ALTER TABLE tarefas
    ADD CONSTRAINT FK_TAREFAS_ON_EMPRESA FOREIGN KEY (empresa_id) REFERENCES empresas (id);