CREATE TABLE colaboradores
(
    id               BIGINT GENERATED BY DEFAULT AS IDENTITY   NOT NULL,
    sequencial       BIGINT                                    NOT NULL,
    matricula        VARCHAR(20)                               NOT NULL,
    nome             VARCHAR(80)                               NOT NULL,
    turma_id         BIGINT                                    NOT NULL,
    empresa_id       BIGINT                                    NOT NULL,
    ativo            BOOLEAN default true                      NOT NULL,
    data_criacao     TIMESTAMP WITHOUT TIME ZONE default now() NOT NULL,
    data_atualizacao TIMESTAMP WITHOUT TIME ZONE               NOT NULL,
    CONSTRAINT pk_colaboradores PRIMARY KEY (id)
);

ALTER TABLE colaboradores ADD CONSTRAINT FK_COLABORADORES_ON_EMPRESA
FOREIGN KEY (empresa_id) REFERENCES empresas (id);

ALTER TABLE colaboradores ADD CONSTRAINT FK_COLABORADORES_ON_TURMA
FOREIGN KEY (turma_id) REFERENCES turmas (id);
