CREATE TABLE cidades
(
    id               VARCHAR(7)           NOT NULL,
    nome             VARCHAR(80)          NOT NULL,
    estado           VARCHAR(2)           NOT NULL,
    data_criacao     date                 NOT NULL,
    data_desativacao date                         ,
    ativo            BOOLEAN default true NOT NULL,
    CONSTRAINT pk_cidades PRIMARY KEY (id)
);

CREATE TABLE proprietarios
(
    id               BIGINT GENERATED BY DEFAULT AS IDENTITY   NOT NULL,
    nome_completo    VARCHAR(100)                              NOT NULL,
    cpf              VARCHAR(14)                               NOT NULL,
    email            VARCHAR(100)                              NOT NULL,
    telefone         VARCHAR(15)                               NOT NULL,
    data_nascimento  date                                      NOT NULL,
    empresa_id       BIGINT                                    NOT NULL,
    ativo            BOOLEAN                                   NOT NULL,
    data_criacao     TIMESTAMP WITHOUT TIME ZONE default now() NOT NULL,
    data_atualizacao TIMESTAMP WITHOUT TIME ZONE default now() NOT NULL,
    controle         VARCHAR(10)                               NOT NULL,
    CONSTRAINT pk_proprietarios PRIMARY KEY (id)
);

ALTER TABLE proprietarios
    ADD CONSTRAINT FK_PROPRIETARIOS_ON_EMPRESA FOREIGN KEY (empresa_id) REFERENCES empresas (id);